export const ROUTE_PATHS = {
  root: "/",
  home: "/",
  mealKits: "/mealkits",
  product: "/product",
  cart: "/cart",
  checkout: "/checkout",
  blog: "/blog",
  blogDetail: "/blog/:slug",
  contact: "/contact",
  orderConfirmed: "/order-confirmed",
  orderTracking: "/track-order",
  howItWorksPage: "/how-it-works",
  login: "/auth/login",
  signup: "/auth/signup",
  userDashboard: "/user/dashboard",
  userDashboardFavorites: "/user/dashboard/favorites",
  userDashboardOrders: "/user/dashboard/orders",
  userDashboardProfile: "/user/dashboard/profile",
  admin: "/admin",
  adminDashboard: "/admin/dashboard",
  adminOrders: "/admin/orders",
  adminUsers: "/admin/users",
  adminProducts: "/admin/products",
  adminBlogs: "/admin/blogs",
  adminLogin: "/admin-login"
};
